<?php

require_once "dedup.php";

function dedup_user($name)
{
	global $migrate_dedup_users;
	if($name != null && array_key_exists($name, $migrate_dedup_users))
		return $migrate_dedup_users[$name];
	
	return $name;
}

$spammails = array(
	"guccibagshere.com",
	"luxurychanel.com",
	"lvforyouonlynow.com",
	"funkyjerseysof.com",
	"buyhermeshere.com",
	"pradahotonsale.com",
	"jointolouisvuitton.com",
	"classicnfljersey.com",
	"mailwithyou.com",
	"scsmalls.com",
	"pradanewstyle.com",
	"vixmalls.com",
	"showcoachfactory.com",
	"momalls.com",
	"bestguccibags.com");

$bf_blender_categories = array();
$bf_blender_categories["None"] = null;
$bf_blender_categories["Animation system"] = "Animation";
$bf_blender_categories["Audio"] = "Audio";
$bf_blender_categories["Compositor"] = "Compositing";
$bf_blender_categories["Depsgraph"] = "Dependency Graph";
$bf_blender_categories["FFMPEG"] = "Images & Movies";
$bf_blender_categories["Freestyle"] = "Freestyle";
$bf_blender_categories["Image &amp; Movie I/O"] = "Images & Movies";
$bf_blender_categories["Import/Export"] = "Import/Export";
$bf_blender_categories["Interface"] = "User Interface";
$bf_blender_categories["International"] = "Translations";
$bf_blender_categories["Masking"] = "Masking";
$bf_blender_categories["Mesh Modeling"] = "Mesh Modeling";
$bf_blender_categories["Modifiers"] = "Modifiers";
$bf_blender_categories["Motion tracking"] = "Motion Tracking";
$bf_blender_categories["Node Editor"] = "Nodes";
$bf_blender_categories["OS related: FreeBSD"] = "FreeBSD";
$bf_blender_categories["OS related: Linux"] = "Linux";
$bf_blender_categories["OS related: OSX"] = "Mac OS X";
$bf_blender_categories["OS related: Windows"] = "Windows";
$bf_blender_categories["Opengl / Gfx"] = "OpenGL / Gfx";
$bf_blender_categories["Physics"] = "Physics";
$bf_blender_categories["Python"] = "Python";
$bf_blender_categories["Rendering"] = "Rendering";
$bf_blender_categories["Rendering: Cycles"] = "Cycles";
$bf_blender_categories["Scripts"] = null;
$bf_blender_categories["Sculpting"] = "Sculpting";
$bf_blender_categories["Sequencer"] = "Video Sequencer";
$bf_blender_categories["Text editor"] = "Text Editor";
$bf_blender_categories["Tools"] = null;
$bf_blender_categories["Game engine"] = "Game Engine";
$bf_blender_categories["Python API"] = "Python";
$bf_blender_categories["nodes and composting"] = "Nodes";

// 89
$bf_developers = array(
	"ack-err",
	"alexk",
	"aligorith",
	"apinzonf",
	"aramis_acg",
	"artificer",
	"bdiego",
	"ben2610",
	"billrey",
	"bjornmose",
	"blendix",
	"briggs",
	"broadstu",
	"broken",
	"campbellbarton",
	"carter24",
	"cessen",
	"cyborgmuppet",
	"dail",
	"dfelinto",
	"dingto",
	"dna",
	"domino",
	"elubie",
	"ender79",
	"erwin",
	"gaiaclary",
	"gdh",
	"genscher",
	"gsrb3d",
	"hos",
	"howardt",
	"irie",
	"jason_hays22",
	"jbakker",
	"jehuty",
	"jensverwiebe",
	"jesterking",
	"jhk",
	"jiri",
	"joeedh",
	"jta",
	"juicyfruit",
	"jwilkins",
	"kazanbas",
	"keir",
	"kjym3",
	"kupoman",
	"kwk",
	"letterrip",
	"lfrisken",
	"lmg",
	"lockal",
	"lukastoenne",
	"mdewanchand",
	"merwin",
	"mfoxdogg",
	"miikah",
	"mindrones",
	"mmikkelsen",
	"moguri",
	"mokazon",
	"mont29",
	"nazgul",
	"nexyon",
	"nicholas_rishel",
	"nicholasbishop",
	"phabtar",
	"plasmasolutions",
	"psy-fi",
	"schlaile",
	"scourage",
	"sergof",
	"sftrabbit",
	"shadowrom",
	"sirdude",
	"sjoerddevries",
	"theeth",
	"ton",
	"trumanblending",
	"vekoon",
	"venomgfx",
	"vino",
	"walid",
	"xercesblue",
	"xglasyliax",
	"yakca",
	"z0r",
	"zanqdo");

// 155
$addon_developers = array(
	"aeonsien",
	"aermartin",
	"aligorith",
	"amorilia",
	"anfeo",
	"antont",
	"anuprao",
	"aurel",
	"axon_d",
	"bartekskorupa",
	"bassamk",
	"bat3a",
	"benjycook",
	"benoitmuller",
	"beta-tester",
	"blendix",
	"blendphys",
	"briggs",
	"brikbot",
	"broken",
	"campbellbarton",
	"carlospadial",
	"carter24",
	"cessen",
	"cnd",
	"codemanx",
	"coledingraham",
	"conz",
	"cotejrp1",
	"crazycourier",
	"crouch",
	"dairin0d",
	"darknet",
	"dfelinto",
	"dingto",
	"dmbasso",
	"dna",
	"dougal2",
	"dreampainter",
	"eclectiel",
	"erwin",
	"forte",
	"freejack",
	"frigi",
	"fsiddi",
	"funkywyrm",
	"gabhead",
	"gaiaclary",
	"gekko",
	"greylica",
	"gsrb3d",
	"guillaum",
	"haikalle",
	"hartsantler",
	"howardt",
	"ianwill",
	"iluvblender",
	"imoverclocked",
	"jacepriester",
	"jambay",
	"jaydez",
	"jbakker",
	"jcbdigger",
	"jensverwiebe",
	"jesterking",
	"jhk",
	"jimmyhaze",
	"joeedh",
	"jos",
	"kai-cent",
	"ken9",
	"kerbox",
	"kgeogeo",
	"khughes",
	"kilon",
	"kiravakaan",
	"kodemax",
	"kromar",
	"kroopson",
	"krypt77",
	"kursadk",
	"leifandersen",
	"letterrip",
	"lichtwerk",
	"liero",
	"liquidape",
	"littleneo",
	"lmg",
	"loolarge",
	"lukast",
	"lukastoenne",
	"mackraken",
	"macouno",
	"majic79",
	"mattreid9956",
	"mauriceraybaud",
	"meta-androcto",
	"mfoxdogg",
	"michaelw",
	"mifth",
	"migius",
	"mindrones",
	"moguri",
	"mont29",
	"muraj",
	"murattige",
	"nazgul",
	"nichod",
	"nrk",
	"oenvoyage",
	"olafarnold",
	"oneliner",
	"oscurart",
	"ov3rright",
	"paleajed",
	"paprmh",
	"paulo_gomes",
	"petercassetta",
	"pildanovak",
	"pkhg",
	"pontiac",
	"reduz",
	"revolt_randy",
	"richardolsson",
	"ruesp83",
	"schlaile",
	"scourage",
	"seminumerical",
	"sirdude",
	"spudmn",
	"stiv",
	"teldredge",
	"testscreenings",
	"tetron",
	"theeth",
	"thefallenweeble",
	"thomasl",
	"ton",
	"totoro",
	"trebor",
	"trumanblending",
	"turi",
	"unhurdof",
	"valtervb",
	"varkenvarken",
	"veliv",
	"vencax",
	"venomgfx",
	"vlassius",
	"wahooney",
	"wiseman303",
	"xat",
	"xembie",
	"zanqdo",
	"zeffii");

// 74
$translation_developers = array(
	"aditiapratama",
	"aituryai",
	"albru123",
	"alirm",
	"antoniodoblas",
	"bartem",
	"bat3a",
	"blendix",
	"campbellbarton",
	"chaos",
	"chingis",
	"codemanx",
	"congcong009",
	"daffi",
	"darkstar",
	"dbugslayer",
	"dfelinto",
	"dorotanm",
	"draakon76",
	"dsavi",
	"eshcharc",
	"ethiojob",
	"exedesign",
	"gab3d",
	"gaiaclary",
	"gotwig",
	"gregorein",
	"greylica",
	"guybrush88",
	"halamix2",
	"hizaro",
	"ideasman42",
	"jesterking",
	"juasjuas",
	"leandrobp",
	"leomoon",
	"leon_cheung",
	"lightning4",
	"livingsilver94",
	"lockal",
	"lxlalexlxl",
	"m13253",
	"manda",
	"mansil",
	"mark_aka_dark",
	"mf0102",
	"monsieur",
	"mont29",
	"natasa",
	"nazgul",
	"ndundupan",
	"nikoola",
	"nikprodanov",
	"nobbz",
	"odil24",
	"pomi",
	"purusoth_uae",
	"qin",
	"rafarios",
	"roshan",
	"santiagolizardo",
	"sergiocumar",
	"sip",
	"sliders",
	"sntulix",
	"taby",
	"taijuin",
	"tim_occ",
	"uriypet",
	"valtervb",
	"xiaoxiangquan",
	"yamyam",
	"yudhir",
	"zerng07");

$admins = array(
	"blendix",
	"ton",
	"jesterking",
	"nazgul",
	"campbellbarton",
	"dmcgrath");

